export const NFTs = [
  {
    Id: 1,
    Badge: "Total Sale: $82,571",
    ImageUrl: "/images/newraw/1.jpeg",
    Edition: 371,
    Stock: "Available",
    Title: "The Coolest",
    Price: "$10M",

    Avatar: "/images/newraw/luffy.jpeg",
    Author: "Nika",
    Likes: 652,
  },
  {
    Id: 2,
    Badge: "Total Sale: $82,571",
    ImageUrl: "/images/newraw/1.jpeg",
    Edition: 371,
    Stock: "Available",
    Title: "The Coolest",
    Price: "$10M",
    Avatar: "/images/newraw/luffy.jpeg",
    Author: "Nika",
    Likes: 652,
  },
  {
    Id: 3,
    Badge: "Total Sale: $82,571",
    ImageUrl: "/images/newraw/1.jpeg",
    Edition: 371,
    Stock: "Available",
    Title: "The Coolest NFT",
    Price: "$10M",
    Avatar: "/images/newraw/luffy.jpeg",
    Author: "Nika",
    Likes: 652,
  },
  {
    Id: 4,
    Badge: "Total Sale: $82,571",
    ImageUrl: "/images/newraw/1.jpeg",
    Edition: 371,
    Stock: "Available",
    Title: "The Coolest",
    Price: "$10M",
    Avatar: "/images/newraw/luffy.jpeg",
    Author: "Nika",
    Likes: 652,
  },
  {
    Id: 5,
    Badge: "Total Sale: $82,571",
    ImageUrl: "/images/newraw/1.jpeg",
    Edition: 371,
    Stock: "Available",
    Title: "The Coolest",
    Price: "$10M",
    Avatar: "/images/newraw/luffy.jpeg",
    Author: "Nika",
    Likes: 652,
  },
  {
    Id: 6,
    Badge: "Total Sale: $82,571",
    ImageUrl: "/images/newraw/1.jpeg",
    Edition: 371,
    Stock: "Available",
    Title: "The Coolest",
    Price: "$10M",
    Avatar: "/images/newraw/luffy.jpeg",
    Author: "Nika",
    Likes: 652,
  },
];
